/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoOrgRouteImport } from './routes/no-org'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as OrgsOrgRouteImport } from './routes/orgs/$org'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ConfirmRegistrationTokenRouteImport } from './routes/confirm-registration.$token'
import { Route as OrgsOrgIndexRouteImport } from './routes/orgs/$org/index'
import { Route as OrgsOrgTestRouteImport } from './routes/orgs/$org/test'
import { Route as OrgsOrgStatusPagesRouteImport } from './routes/orgs/$org/status-pages'
import { Route as OrgsOrgServerRouteImport } from './routes/orgs/$org/server'
import { Route as OrgsOrgRegisterRouteImport } from './routes/orgs/$org/register'
import { Route as OrgsOrgOrganizationRouteImport } from './routes/orgs/$org/organization'
import { Route as OrgsOrgLoginRouteImport } from './routes/orgs/$org/login'
import { Route as OrgsOrgIncidentsRouteImport } from './routes/orgs/$org/incidents'
import { Route as OrgsOrgEventsRouteImport } from './routes/orgs/$org/events'
import { Route as OrgsOrgChecksRouteImport } from './routes/orgs/$org/checks'
import { Route as OrgsOrgBadgesRouteImport } from './routes/orgs/$org/badges'
import { Route as OrgsOrgAccountRouteImport } from './routes/orgs/$org/account'
import { Route as AuthSlackCompleteRouteImport } from './routes/auth.slack.complete'
import { Route as OrgsOrgTestIndexRouteImport } from './routes/orgs/$org/test.index'
import { Route as OrgsOrgStatusPagesIndexRouteImport } from './routes/orgs/$org/status-pages.index'
import { Route as OrgsOrgServerIndexRouteImport } from './routes/orgs/$org/server.index'
import { Route as OrgsOrgOrganizationIndexRouteImport } from './routes/orgs/$org/organization.index'
import { Route as OrgsOrgIncidentsIndexRouteImport } from './routes/orgs/$org/incidents.index'
import { Route as OrgsOrgChecksIndexRouteImport } from './routes/orgs/$org/checks.index'
import { Route as OrgsOrgAccountIndexRouteImport } from './routes/orgs/$org/account.index'
import { Route as OrgsOrgTestTemplatesRouteImport } from './routes/orgs/$org/test.templates'
import { Route as OrgsOrgTestResetRouteImport } from './routes/orgs/$org/test.reset'
import { Route as OrgsOrgTestGenerateRouteImport } from './routes/orgs/$org/test.generate'
import { Route as OrgsOrgTestBulkRouteImport } from './routes/orgs/$org/test.bulk'
import { Route as OrgsOrgStatusPagesNewRouteImport } from './routes/orgs/$org/status-pages.new'
import { Route as OrgsOrgStatusPagesStatusPageUidRouteImport } from './routes/orgs/$org/status-pages.$statusPageUid'
import { Route as OrgsOrgServerWebRouteImport } from './routes/orgs/$org/server.web'
import { Route as OrgsOrgServerPerformanceRouteImport } from './routes/orgs/$org/server.performance'
import { Route as OrgsOrgServerMailRouteImport } from './routes/orgs/$org/server.mail'
import { Route as OrgsOrgServerEmailInboxRouteImport } from './routes/orgs/$org/server.email-inbox'
import { Route as OrgsOrgServerAuthRouteImport } from './routes/orgs/$org/server.auth'
import { Route as OrgsOrgOrganizationSettingsRouteImport } from './routes/orgs/$org/organization.settings'
import { Route as OrgsOrgOrganizationInvitationsRouteImport } from './routes/orgs/$org/organization.invitations'
import { Route as OrgsOrgIncidentsIncidentUidRouteImport } from './routes/orgs/$org/incidents.$incidentUid'
import { Route as OrgsOrgChecksNewRouteImport } from './routes/orgs/$org/checks.new'
import { Route as OrgsOrgChecksCheckUidRouteImport } from './routes/orgs/$org/checks.$checkUid'
import { Route as OrgsOrgAccountTokensRouteImport } from './routes/orgs/$org/account.tokens'
import { Route as OrgsOrgAccountProfileRouteImport } from './routes/orgs/$org/account.profile'
import { Route as OrgsOrgStatusPagesStatusPageUidIndexRouteImport } from './routes/orgs/$org/status-pages.$statusPageUid.index'
import { Route as OrgsOrgChecksCheckUidIndexRouteImport } from './routes/orgs/$org/checks.$checkUid.index'
import { Route as OrgsOrgStatusPagesStatusPageUidEditRouteImport } from './routes/orgs/$org/status-pages.$statusPageUid.edit'
import { Route as OrgsOrgChecksCheckUidEditRouteImport } from './routes/orgs/$org/checks.$checkUid.edit'
import { Route as OrgsOrgChecksCheckUidResultsResultUidRouteImport } from './routes/orgs/$org/checks.$checkUid.results.$resultUid'

const NoOrgRoute = NoOrgRouteImport.update({
  id: '/no-org',
  path: '/no-org',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgRoute = OrgsOrgRouteImport.update({
  id: '/orgs/$org',
  path: '/orgs/$org',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRegistrationTokenRoute =
  ConfirmRegistrationTokenRouteImport.update({
    id: '/confirm-registration/$token',
    path: '/confirm-registration/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgsOrgIndexRoute = OrgsOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgsOrgRoute,
} as any)
const OrgsOrgTestRoute = OrgsOrgTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => OrgsOrgRoute,
} as any)
const OrgsOrgStatusPagesRoute = OrgsOrgStatusPagesRouteImport.update({
  id: '/status-pages',
  path: '/status-pages',
  getParentRoute: () => OrgsOrgRoute,
} as any)
const OrgsOrgServerRoute = OrgsOrgServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => OrgsOrgRoute,
} as any)
const OrgsOrgRegisterRoute = OrgsOrgRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => OrgsOrgRoute,
} as any)
const OrgsOrgOrganizationRoute = OrgsOrgOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => OrgsOrgRoute,
} as any)
const OrgsOrgLoginRoute = OrgsOrgLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OrgsOrgRoute,
} as any)
const OrgsOrgIncidentsRoute = OrgsOrgIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => OrgsOrgRoute,
} as any)
const OrgsOrgEventsRoute = OrgsOrgEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => OrgsOrgRoute,
} as any)
const OrgsOrgChecksRoute = OrgsOrgChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => OrgsOrgRoute,
} as any)
const OrgsOrgBadgesRoute = OrgsOrgBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => OrgsOrgRoute,
} as any)
const OrgsOrgAccountRoute = OrgsOrgAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => OrgsOrgRoute,
} as any)
const AuthSlackCompleteRoute = AuthSlackCompleteRouteImport.update({
  id: '/auth/slack/complete',
  path: '/auth/slack/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgTestIndexRoute = OrgsOrgTestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgsOrgTestRoute,
} as any)
const OrgsOrgStatusPagesIndexRoute = OrgsOrgStatusPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgsOrgStatusPagesRoute,
} as any)
const OrgsOrgServerIndexRoute = OrgsOrgServerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgsOrgServerRoute,
} as any)
const OrgsOrgOrganizationIndexRoute =
  OrgsOrgOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgsOrgOrganizationRoute,
  } as any)
const OrgsOrgIncidentsIndexRoute = OrgsOrgIncidentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgsOrgIncidentsRoute,
} as any)
const OrgsOrgChecksIndexRoute = OrgsOrgChecksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgsOrgChecksRoute,
} as any)
const OrgsOrgAccountIndexRoute = OrgsOrgAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgsOrgAccountRoute,
} as any)
const OrgsOrgTestTemplatesRoute = OrgsOrgTestTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => OrgsOrgTestRoute,
} as any)
const OrgsOrgTestResetRoute = OrgsOrgTestResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => OrgsOrgTestRoute,
} as any)
const OrgsOrgTestGenerateRoute = OrgsOrgTestGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => OrgsOrgTestRoute,
} as any)
const OrgsOrgTestBulkRoute = OrgsOrgTestBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => OrgsOrgTestRoute,
} as any)
const OrgsOrgStatusPagesNewRoute = OrgsOrgStatusPagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrgsOrgStatusPagesRoute,
} as any)
const OrgsOrgStatusPagesStatusPageUidRoute =
  OrgsOrgStatusPagesStatusPageUidRouteImport.update({
    id: '/$statusPageUid',
    path: '/$statusPageUid',
    getParentRoute: () => OrgsOrgStatusPagesRoute,
  } as any)
const OrgsOrgServerWebRoute = OrgsOrgServerWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => OrgsOrgServerRoute,
} as any)
const OrgsOrgServerPerformanceRoute =
  OrgsOrgServerPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => OrgsOrgServerRoute,
  } as any)
const OrgsOrgServerMailRoute = OrgsOrgServerMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => OrgsOrgServerRoute,
} as any)
const OrgsOrgServerEmailInboxRoute = OrgsOrgServerEmailInboxRouteImport.update({
  id: '/email-inbox',
  path: '/email-inbox',
  getParentRoute: () => OrgsOrgServerRoute,
} as any)
const OrgsOrgServerAuthRoute = OrgsOrgServerAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => OrgsOrgServerRoute,
} as any)
const OrgsOrgOrganizationSettingsRoute =
  OrgsOrgOrganizationSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrgsOrgOrganizationRoute,
  } as any)
const OrgsOrgOrganizationInvitationsRoute =
  OrgsOrgOrganizationInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => OrgsOrgOrganizationRoute,
  } as any)
const OrgsOrgIncidentsIncidentUidRoute =
  OrgsOrgIncidentsIncidentUidRouteImport.update({
    id: '/$incidentUid',
    path: '/$incidentUid',
    getParentRoute: () => OrgsOrgIncidentsRoute,
  } as any)
const OrgsOrgChecksNewRoute = OrgsOrgChecksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrgsOrgChecksRoute,
} as any)
const OrgsOrgChecksCheckUidRoute = OrgsOrgChecksCheckUidRouteImport.update({
  id: '/$checkUid',
  path: '/$checkUid',
  getParentRoute: () => OrgsOrgChecksRoute,
} as any)
const OrgsOrgAccountTokensRoute = OrgsOrgAccountTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => OrgsOrgAccountRoute,
} as any)
const OrgsOrgAccountProfileRoute = OrgsOrgAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OrgsOrgAccountRoute,
} as any)
const OrgsOrgStatusPagesStatusPageUidIndexRoute =
  OrgsOrgStatusPagesStatusPageUidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgsOrgStatusPagesStatusPageUidRoute,
  } as any)
const OrgsOrgChecksCheckUidIndexRoute =
  OrgsOrgChecksCheckUidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgsOrgChecksCheckUidRoute,
  } as any)
const OrgsOrgStatusPagesStatusPageUidEditRoute =
  OrgsOrgStatusPagesStatusPageUidEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => OrgsOrgStatusPagesStatusPageUidRoute,
  } as any)
const OrgsOrgChecksCheckUidEditRoute =
  OrgsOrgChecksCheckUidEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => OrgsOrgChecksCheckUidRoute,
  } as any)
const OrgsOrgChecksCheckUidResultsResultUidRoute =
  OrgsOrgChecksCheckUidResultsResultUidRouteImport.update({
    id: '/results/$resultUid',
    path: '/results/$resultUid',
    getParentRoute: () => OrgsOrgChecksCheckUidRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/no-org': typeof NoOrgRoute
  '/confirm-registration/$token': typeof ConfirmRegistrationTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/orgs/$org': typeof OrgsOrgRouteWithChildren
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/auth/slack/complete': typeof AuthSlackCompleteRoute
  '/orgs/$org/account': typeof OrgsOrgAccountRouteWithChildren
  '/orgs/$org/badges': typeof OrgsOrgBadgesRoute
  '/orgs/$org/checks': typeof OrgsOrgChecksRouteWithChildren
  '/orgs/$org/events': typeof OrgsOrgEventsRoute
  '/orgs/$org/incidents': typeof OrgsOrgIncidentsRouteWithChildren
  '/orgs/$org/login': typeof OrgsOrgLoginRoute
  '/orgs/$org/organization': typeof OrgsOrgOrganizationRouteWithChildren
  '/orgs/$org/register': typeof OrgsOrgRegisterRoute
  '/orgs/$org/server': typeof OrgsOrgServerRouteWithChildren
  '/orgs/$org/status-pages': typeof OrgsOrgStatusPagesRouteWithChildren
  '/orgs/$org/test': typeof OrgsOrgTestRouteWithChildren
  '/orgs/$org/': typeof OrgsOrgIndexRoute
  '/orgs/$org/account/profile': typeof OrgsOrgAccountProfileRoute
  '/orgs/$org/account/tokens': typeof OrgsOrgAccountTokensRoute
  '/orgs/$org/checks/$checkUid': typeof OrgsOrgChecksCheckUidRouteWithChildren
  '/orgs/$org/checks/new': typeof OrgsOrgChecksNewRoute
  '/orgs/$org/incidents/$incidentUid': typeof OrgsOrgIncidentsIncidentUidRoute
  '/orgs/$org/organization/invitations': typeof OrgsOrgOrganizationInvitationsRoute
  '/orgs/$org/organization/settings': typeof OrgsOrgOrganizationSettingsRoute
  '/orgs/$org/server/auth': typeof OrgsOrgServerAuthRoute
  '/orgs/$org/server/email-inbox': typeof OrgsOrgServerEmailInboxRoute
  '/orgs/$org/server/mail': typeof OrgsOrgServerMailRoute
  '/orgs/$org/server/performance': typeof OrgsOrgServerPerformanceRoute
  '/orgs/$org/server/web': typeof OrgsOrgServerWebRoute
  '/orgs/$org/status-pages/$statusPageUid': typeof OrgsOrgStatusPagesStatusPageUidRouteWithChildren
  '/orgs/$org/status-pages/new': typeof OrgsOrgStatusPagesNewRoute
  '/orgs/$org/test/bulk': typeof OrgsOrgTestBulkRoute
  '/orgs/$org/test/generate': typeof OrgsOrgTestGenerateRoute
  '/orgs/$org/test/reset': typeof OrgsOrgTestResetRoute
  '/orgs/$org/test/templates': typeof OrgsOrgTestTemplatesRoute
  '/orgs/$org/account/': typeof OrgsOrgAccountIndexRoute
  '/orgs/$org/checks/': typeof OrgsOrgChecksIndexRoute
  '/orgs/$org/incidents/': typeof OrgsOrgIncidentsIndexRoute
  '/orgs/$org/organization/': typeof OrgsOrgOrganizationIndexRoute
  '/orgs/$org/server/': typeof OrgsOrgServerIndexRoute
  '/orgs/$org/status-pages/': typeof OrgsOrgStatusPagesIndexRoute
  '/orgs/$org/test/': typeof OrgsOrgTestIndexRoute
  '/orgs/$org/checks/$checkUid/edit': typeof OrgsOrgChecksCheckUidEditRoute
  '/orgs/$org/status-pages/$statusPageUid/edit': typeof OrgsOrgStatusPagesStatusPageUidEditRoute
  '/orgs/$org/checks/$checkUid/': typeof OrgsOrgChecksCheckUidIndexRoute
  '/orgs/$org/status-pages/$statusPageUid/': typeof OrgsOrgStatusPagesStatusPageUidIndexRoute
  '/orgs/$org/checks/$checkUid/results/$resultUid': typeof OrgsOrgChecksCheckUidResultsResultUidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/no-org': typeof NoOrgRoute
  '/confirm-registration/$token': typeof ConfirmRegistrationTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/auth/slack/complete': typeof AuthSlackCompleteRoute
  '/orgs/$org/badges': typeof OrgsOrgBadgesRoute
  '/orgs/$org/events': typeof OrgsOrgEventsRoute
  '/orgs/$org/login': typeof OrgsOrgLoginRoute
  '/orgs/$org/register': typeof OrgsOrgRegisterRoute
  '/orgs/$org': typeof OrgsOrgIndexRoute
  '/orgs/$org/account/profile': typeof OrgsOrgAccountProfileRoute
  '/orgs/$org/account/tokens': typeof OrgsOrgAccountTokensRoute
  '/orgs/$org/checks/new': typeof OrgsOrgChecksNewRoute
  '/orgs/$org/incidents/$incidentUid': typeof OrgsOrgIncidentsIncidentUidRoute
  '/orgs/$org/organization/invitations': typeof OrgsOrgOrganizationInvitationsRoute
  '/orgs/$org/organization/settings': typeof OrgsOrgOrganizationSettingsRoute
  '/orgs/$org/server/auth': typeof OrgsOrgServerAuthRoute
  '/orgs/$org/server/email-inbox': typeof OrgsOrgServerEmailInboxRoute
  '/orgs/$org/server/mail': typeof OrgsOrgServerMailRoute
  '/orgs/$org/server/performance': typeof OrgsOrgServerPerformanceRoute
  '/orgs/$org/server/web': typeof OrgsOrgServerWebRoute
  '/orgs/$org/status-pages/new': typeof OrgsOrgStatusPagesNewRoute
  '/orgs/$org/test/bulk': typeof OrgsOrgTestBulkRoute
  '/orgs/$org/test/generate': typeof OrgsOrgTestGenerateRoute
  '/orgs/$org/test/reset': typeof OrgsOrgTestResetRoute
  '/orgs/$org/test/templates': typeof OrgsOrgTestTemplatesRoute
  '/orgs/$org/account': typeof OrgsOrgAccountIndexRoute
  '/orgs/$org/checks': typeof OrgsOrgChecksIndexRoute
  '/orgs/$org/incidents': typeof OrgsOrgIncidentsIndexRoute
  '/orgs/$org/organization': typeof OrgsOrgOrganizationIndexRoute
  '/orgs/$org/server': typeof OrgsOrgServerIndexRoute
  '/orgs/$org/status-pages': typeof OrgsOrgStatusPagesIndexRoute
  '/orgs/$org/test': typeof OrgsOrgTestIndexRoute
  '/orgs/$org/checks/$checkUid/edit': typeof OrgsOrgChecksCheckUidEditRoute
  '/orgs/$org/status-pages/$statusPageUid/edit': typeof OrgsOrgStatusPagesStatusPageUidEditRoute
  '/orgs/$org/checks/$checkUid': typeof OrgsOrgChecksCheckUidIndexRoute
  '/orgs/$org/status-pages/$statusPageUid': typeof OrgsOrgStatusPagesStatusPageUidIndexRoute
  '/orgs/$org/checks/$checkUid/results/$resultUid': typeof OrgsOrgChecksCheckUidResultsResultUidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/no-org': typeof NoOrgRoute
  '/confirm-registration/$token': typeof ConfirmRegistrationTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/orgs/$org': typeof OrgsOrgRouteWithChildren
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/auth/slack/complete': typeof AuthSlackCompleteRoute
  '/orgs/$org/account': typeof OrgsOrgAccountRouteWithChildren
  '/orgs/$org/badges': typeof OrgsOrgBadgesRoute
  '/orgs/$org/checks': typeof OrgsOrgChecksRouteWithChildren
  '/orgs/$org/events': typeof OrgsOrgEventsRoute
  '/orgs/$org/incidents': typeof OrgsOrgIncidentsRouteWithChildren
  '/orgs/$org/login': typeof OrgsOrgLoginRoute
  '/orgs/$org/organization': typeof OrgsOrgOrganizationRouteWithChildren
  '/orgs/$org/register': typeof OrgsOrgRegisterRoute
  '/orgs/$org/server': typeof OrgsOrgServerRouteWithChildren
  '/orgs/$org/status-pages': typeof OrgsOrgStatusPagesRouteWithChildren
  '/orgs/$org/test': typeof OrgsOrgTestRouteWithChildren
  '/orgs/$org/': typeof OrgsOrgIndexRoute
  '/orgs/$org/account/profile': typeof OrgsOrgAccountProfileRoute
  '/orgs/$org/account/tokens': typeof OrgsOrgAccountTokensRoute
  '/orgs/$org/checks/$checkUid': typeof OrgsOrgChecksCheckUidRouteWithChildren
  '/orgs/$org/checks/new': typeof OrgsOrgChecksNewRoute
  '/orgs/$org/incidents/$incidentUid': typeof OrgsOrgIncidentsIncidentUidRoute
  '/orgs/$org/organization/invitations': typeof OrgsOrgOrganizationInvitationsRoute
  '/orgs/$org/organization/settings': typeof OrgsOrgOrganizationSettingsRoute
  '/orgs/$org/server/auth': typeof OrgsOrgServerAuthRoute
  '/orgs/$org/server/email-inbox': typeof OrgsOrgServerEmailInboxRoute
  '/orgs/$org/server/mail': typeof OrgsOrgServerMailRoute
  '/orgs/$org/server/performance': typeof OrgsOrgServerPerformanceRoute
  '/orgs/$org/server/web': typeof OrgsOrgServerWebRoute
  '/orgs/$org/status-pages/$statusPageUid': typeof OrgsOrgStatusPagesStatusPageUidRouteWithChildren
  '/orgs/$org/status-pages/new': typeof OrgsOrgStatusPagesNewRoute
  '/orgs/$org/test/bulk': typeof OrgsOrgTestBulkRoute
  '/orgs/$org/test/generate': typeof OrgsOrgTestGenerateRoute
  '/orgs/$org/test/reset': typeof OrgsOrgTestResetRoute
  '/orgs/$org/test/templates': typeof OrgsOrgTestTemplatesRoute
  '/orgs/$org/account/': typeof OrgsOrgAccountIndexRoute
  '/orgs/$org/checks/': typeof OrgsOrgChecksIndexRoute
  '/orgs/$org/incidents/': typeof OrgsOrgIncidentsIndexRoute
  '/orgs/$org/organization/': typeof OrgsOrgOrganizationIndexRoute
  '/orgs/$org/server/': typeof OrgsOrgServerIndexRoute
  '/orgs/$org/status-pages/': typeof OrgsOrgStatusPagesIndexRoute
  '/orgs/$org/test/': typeof OrgsOrgTestIndexRoute
  '/orgs/$org/checks/$checkUid/edit': typeof OrgsOrgChecksCheckUidEditRoute
  '/orgs/$org/status-pages/$statusPageUid/edit': typeof OrgsOrgStatusPagesStatusPageUidEditRoute
  '/orgs/$org/checks/$checkUid/': typeof OrgsOrgChecksCheckUidIndexRoute
  '/orgs/$org/status-pages/$statusPageUid/': typeof OrgsOrgStatusPagesStatusPageUidIndexRoute
  '/orgs/$org/checks/$checkUid/results/$resultUid': typeof OrgsOrgChecksCheckUidResultsResultUidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/no-org'
    | '/confirm-registration/$token'
    | '/invite/$token'
    | '/orgs/$org'
    | '/reset-password/$token'
    | '/auth/slack/complete'
    | '/orgs/$org/account'
    | '/orgs/$org/badges'
    | '/orgs/$org/checks'
    | '/orgs/$org/events'
    | '/orgs/$org/incidents'
    | '/orgs/$org/login'
    | '/orgs/$org/organization'
    | '/orgs/$org/register'
    | '/orgs/$org/server'
    | '/orgs/$org/status-pages'
    | '/orgs/$org/test'
    | '/orgs/$org/'
    | '/orgs/$org/account/profile'
    | '/orgs/$org/account/tokens'
    | '/orgs/$org/checks/$checkUid'
    | '/orgs/$org/checks/new'
    | '/orgs/$org/incidents/$incidentUid'
    | '/orgs/$org/organization/invitations'
    | '/orgs/$org/organization/settings'
    | '/orgs/$org/server/auth'
    | '/orgs/$org/server/email-inbox'
    | '/orgs/$org/server/mail'
    | '/orgs/$org/server/performance'
    | '/orgs/$org/server/web'
    | '/orgs/$org/status-pages/$statusPageUid'
    | '/orgs/$org/status-pages/new'
    | '/orgs/$org/test/bulk'
    | '/orgs/$org/test/generate'
    | '/orgs/$org/test/reset'
    | '/orgs/$org/test/templates'
    | '/orgs/$org/account/'
    | '/orgs/$org/checks/'
    | '/orgs/$org/incidents/'
    | '/orgs/$org/organization/'
    | '/orgs/$org/server/'
    | '/orgs/$org/status-pages/'
    | '/orgs/$org/test/'
    | '/orgs/$org/checks/$checkUid/edit'
    | '/orgs/$org/status-pages/$statusPageUid/edit'
    | '/orgs/$org/checks/$checkUid/'
    | '/orgs/$org/status-pages/$statusPageUid/'
    | '/orgs/$org/checks/$checkUid/results/$resultUid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/no-org'
    | '/confirm-registration/$token'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/auth/slack/complete'
    | '/orgs/$org/badges'
    | '/orgs/$org/events'
    | '/orgs/$org/login'
    | '/orgs/$org/register'
    | '/orgs/$org'
    | '/orgs/$org/account/profile'
    | '/orgs/$org/account/tokens'
    | '/orgs/$org/checks/new'
    | '/orgs/$org/incidents/$incidentUid'
    | '/orgs/$org/organization/invitations'
    | '/orgs/$org/organization/settings'
    | '/orgs/$org/server/auth'
    | '/orgs/$org/server/email-inbox'
    | '/orgs/$org/server/mail'
    | '/orgs/$org/server/performance'
    | '/orgs/$org/server/web'
    | '/orgs/$org/status-pages/new'
    | '/orgs/$org/test/bulk'
    | '/orgs/$org/test/generate'
    | '/orgs/$org/test/reset'
    | '/orgs/$org/test/templates'
    | '/orgs/$org/account'
    | '/orgs/$org/checks'
    | '/orgs/$org/incidents'
    | '/orgs/$org/organization'
    | '/orgs/$org/server'
    | '/orgs/$org/status-pages'
    | '/orgs/$org/test'
    | '/orgs/$org/checks/$checkUid/edit'
    | '/orgs/$org/status-pages/$statusPageUid/edit'
    | '/orgs/$org/checks/$checkUid'
    | '/orgs/$org/status-pages/$statusPageUid'
    | '/orgs/$org/checks/$checkUid/results/$resultUid'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/no-org'
    | '/confirm-registration/$token'
    | '/invite/$token'
    | '/orgs/$org'
    | '/reset-password/$token'
    | '/auth/slack/complete'
    | '/orgs/$org/account'
    | '/orgs/$org/badges'
    | '/orgs/$org/checks'
    | '/orgs/$org/events'
    | '/orgs/$org/incidents'
    | '/orgs/$org/login'
    | '/orgs/$org/organization'
    | '/orgs/$org/register'
    | '/orgs/$org/server'
    | '/orgs/$org/status-pages'
    | '/orgs/$org/test'
    | '/orgs/$org/'
    | '/orgs/$org/account/profile'
    | '/orgs/$org/account/tokens'
    | '/orgs/$org/checks/$checkUid'
    | '/orgs/$org/checks/new'
    | '/orgs/$org/incidents/$incidentUid'
    | '/orgs/$org/organization/invitations'
    | '/orgs/$org/organization/settings'
    | '/orgs/$org/server/auth'
    | '/orgs/$org/server/email-inbox'
    | '/orgs/$org/server/mail'
    | '/orgs/$org/server/performance'
    | '/orgs/$org/server/web'
    | '/orgs/$org/status-pages/$statusPageUid'
    | '/orgs/$org/status-pages/new'
    | '/orgs/$org/test/bulk'
    | '/orgs/$org/test/generate'
    | '/orgs/$org/test/reset'
    | '/orgs/$org/test/templates'
    | '/orgs/$org/account/'
    | '/orgs/$org/checks/'
    | '/orgs/$org/incidents/'
    | '/orgs/$org/organization/'
    | '/orgs/$org/server/'
    | '/orgs/$org/status-pages/'
    | '/orgs/$org/test/'
    | '/orgs/$org/checks/$checkUid/edit'
    | '/orgs/$org/status-pages/$statusPageUid/edit'
    | '/orgs/$org/checks/$checkUid/'
    | '/orgs/$org/status-pages/$statusPageUid/'
    | '/orgs/$org/checks/$checkUid/results/$resultUid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NoOrgRoute: typeof NoOrgRoute
  ConfirmRegistrationTokenRoute: typeof ConfirmRegistrationTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OrgsOrgRoute: typeof OrgsOrgRouteWithChildren
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  AuthSlackCompleteRoute: typeof AuthSlackCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/no-org': {
      id: '/no-org'
      path: '/no-org'
      fullPath: '/no-org'
      preLoaderRoute: typeof NoOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$org': {
      id: '/orgs/$org'
      path: '/orgs/$org'
      fullPath: '/orgs/$org'
      preLoaderRoute: typeof OrgsOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-registration/$token': {
      id: '/confirm-registration/$token'
      path: '/confirm-registration/$token'
      fullPath: '/confirm-registration/$token'
      preLoaderRoute: typeof ConfirmRegistrationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$org/': {
      id: '/orgs/$org/'
      path: '/'
      fullPath: '/orgs/$org/'
      preLoaderRoute: typeof OrgsOrgIndexRouteImport
      parentRoute: typeof OrgsOrgRoute
    }
    '/orgs/$org/test': {
      id: '/orgs/$org/test'
      path: '/test'
      fullPath: '/orgs/$org/test'
      preLoaderRoute: typeof OrgsOrgTestRouteImport
      parentRoute: typeof OrgsOrgRoute
    }
    '/orgs/$org/status-pages': {
      id: '/orgs/$org/status-pages'
      path: '/status-pages'
      fullPath: '/orgs/$org/status-pages'
      preLoaderRoute: typeof OrgsOrgStatusPagesRouteImport
      parentRoute: typeof OrgsOrgRoute
    }
    '/orgs/$org/server': {
      id: '/orgs/$org/server'
      path: '/server'
      fullPath: '/orgs/$org/server'
      preLoaderRoute: typeof OrgsOrgServerRouteImport
      parentRoute: typeof OrgsOrgRoute
    }
    '/orgs/$org/register': {
      id: '/orgs/$org/register'
      path: '/register'
      fullPath: '/orgs/$org/register'
      preLoaderRoute: typeof OrgsOrgRegisterRouteImport
      parentRoute: typeof OrgsOrgRoute
    }
    '/orgs/$org/organization': {
      id: '/orgs/$org/organization'
      path: '/organization'
      fullPath: '/orgs/$org/organization'
      preLoaderRoute: typeof OrgsOrgOrganizationRouteImport
      parentRoute: typeof OrgsOrgRoute
    }
    '/orgs/$org/login': {
      id: '/orgs/$org/login'
      path: '/login'
      fullPath: '/orgs/$org/login'
      preLoaderRoute: typeof OrgsOrgLoginRouteImport
      parentRoute: typeof OrgsOrgRoute
    }
    '/orgs/$org/incidents': {
      id: '/orgs/$org/incidents'
      path: '/incidents'
      fullPath: '/orgs/$org/incidents'
      preLoaderRoute: typeof OrgsOrgIncidentsRouteImport
      parentRoute: typeof OrgsOrgRoute
    }
    '/orgs/$org/events': {
      id: '/orgs/$org/events'
      path: '/events'
      fullPath: '/orgs/$org/events'
      preLoaderRoute: typeof OrgsOrgEventsRouteImport
      parentRoute: typeof OrgsOrgRoute
    }
    '/orgs/$org/checks': {
      id: '/orgs/$org/checks'
      path: '/checks'
      fullPath: '/orgs/$org/checks'
      preLoaderRoute: typeof OrgsOrgChecksRouteImport
      parentRoute: typeof OrgsOrgRoute
    }
    '/orgs/$org/badges': {
      id: '/orgs/$org/badges'
      path: '/badges'
      fullPath: '/orgs/$org/badges'
      preLoaderRoute: typeof OrgsOrgBadgesRouteImport
      parentRoute: typeof OrgsOrgRoute
    }
    '/orgs/$org/account': {
      id: '/orgs/$org/account'
      path: '/account'
      fullPath: '/orgs/$org/account'
      preLoaderRoute: typeof OrgsOrgAccountRouteImport
      parentRoute: typeof OrgsOrgRoute
    }
    '/auth/slack/complete': {
      id: '/auth/slack/complete'
      path: '/auth/slack/complete'
      fullPath: '/auth/slack/complete'
      preLoaderRoute: typeof AuthSlackCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$org/test/': {
      id: '/orgs/$org/test/'
      path: '/'
      fullPath: '/orgs/$org/test/'
      preLoaderRoute: typeof OrgsOrgTestIndexRouteImport
      parentRoute: typeof OrgsOrgTestRoute
    }
    '/orgs/$org/status-pages/': {
      id: '/orgs/$org/status-pages/'
      path: '/'
      fullPath: '/orgs/$org/status-pages/'
      preLoaderRoute: typeof OrgsOrgStatusPagesIndexRouteImport
      parentRoute: typeof OrgsOrgStatusPagesRoute
    }
    '/orgs/$org/server/': {
      id: '/orgs/$org/server/'
      path: '/'
      fullPath: '/orgs/$org/server/'
      preLoaderRoute: typeof OrgsOrgServerIndexRouteImport
      parentRoute: typeof OrgsOrgServerRoute
    }
    '/orgs/$org/organization/': {
      id: '/orgs/$org/organization/'
      path: '/'
      fullPath: '/orgs/$org/organization/'
      preLoaderRoute: typeof OrgsOrgOrganizationIndexRouteImport
      parentRoute: typeof OrgsOrgOrganizationRoute
    }
    '/orgs/$org/incidents/': {
      id: '/orgs/$org/incidents/'
      path: '/'
      fullPath: '/orgs/$org/incidents/'
      preLoaderRoute: typeof OrgsOrgIncidentsIndexRouteImport
      parentRoute: typeof OrgsOrgIncidentsRoute
    }
    '/orgs/$org/checks/': {
      id: '/orgs/$org/checks/'
      path: '/'
      fullPath: '/orgs/$org/checks/'
      preLoaderRoute: typeof OrgsOrgChecksIndexRouteImport
      parentRoute: typeof OrgsOrgChecksRoute
    }
    '/orgs/$org/account/': {
      id: '/orgs/$org/account/'
      path: '/'
      fullPath: '/orgs/$org/account/'
      preLoaderRoute: typeof OrgsOrgAccountIndexRouteImport
      parentRoute: typeof OrgsOrgAccountRoute
    }
    '/orgs/$org/test/templates': {
      id: '/orgs/$org/test/templates'
      path: '/templates'
      fullPath: '/orgs/$org/test/templates'
      preLoaderRoute: typeof OrgsOrgTestTemplatesRouteImport
      parentRoute: typeof OrgsOrgTestRoute
    }
    '/orgs/$org/test/reset': {
      id: '/orgs/$org/test/reset'
      path: '/reset'
      fullPath: '/orgs/$org/test/reset'
      preLoaderRoute: typeof OrgsOrgTestResetRouteImport
      parentRoute: typeof OrgsOrgTestRoute
    }
    '/orgs/$org/test/generate': {
      id: '/orgs/$org/test/generate'
      path: '/generate'
      fullPath: '/orgs/$org/test/generate'
      preLoaderRoute: typeof OrgsOrgTestGenerateRouteImport
      parentRoute: typeof OrgsOrgTestRoute
    }
    '/orgs/$org/test/bulk': {
      id: '/orgs/$org/test/bulk'
      path: '/bulk'
      fullPath: '/orgs/$org/test/bulk'
      preLoaderRoute: typeof OrgsOrgTestBulkRouteImport
      parentRoute: typeof OrgsOrgTestRoute
    }
    '/orgs/$org/status-pages/new': {
      id: '/orgs/$org/status-pages/new'
      path: '/new'
      fullPath: '/orgs/$org/status-pages/new'
      preLoaderRoute: typeof OrgsOrgStatusPagesNewRouteImport
      parentRoute: typeof OrgsOrgStatusPagesRoute
    }
    '/orgs/$org/status-pages/$statusPageUid': {
      id: '/orgs/$org/status-pages/$statusPageUid'
      path: '/$statusPageUid'
      fullPath: '/orgs/$org/status-pages/$statusPageUid'
      preLoaderRoute: typeof OrgsOrgStatusPagesStatusPageUidRouteImport
      parentRoute: typeof OrgsOrgStatusPagesRoute
    }
    '/orgs/$org/server/web': {
      id: '/orgs/$org/server/web'
      path: '/web'
      fullPath: '/orgs/$org/server/web'
      preLoaderRoute: typeof OrgsOrgServerWebRouteImport
      parentRoute: typeof OrgsOrgServerRoute
    }
    '/orgs/$org/server/performance': {
      id: '/orgs/$org/server/performance'
      path: '/performance'
      fullPath: '/orgs/$org/server/performance'
      preLoaderRoute: typeof OrgsOrgServerPerformanceRouteImport
      parentRoute: typeof OrgsOrgServerRoute
    }
    '/orgs/$org/server/mail': {
      id: '/orgs/$org/server/mail'
      path: '/mail'
      fullPath: '/orgs/$org/server/mail'
      preLoaderRoute: typeof OrgsOrgServerMailRouteImport
      parentRoute: typeof OrgsOrgServerRoute
    }
    '/orgs/$org/server/email-inbox': {
      id: '/orgs/$org/server/email-inbox'
      path: '/email-inbox'
      fullPath: '/orgs/$org/server/email-inbox'
      preLoaderRoute: typeof OrgsOrgServerEmailInboxRouteImport
      parentRoute: typeof OrgsOrgServerRoute
    }
    '/orgs/$org/server/auth': {
      id: '/orgs/$org/server/auth'
      path: '/auth'
      fullPath: '/orgs/$org/server/auth'
      preLoaderRoute: typeof OrgsOrgServerAuthRouteImport
      parentRoute: typeof OrgsOrgServerRoute
    }
    '/orgs/$org/organization/settings': {
      id: '/orgs/$org/organization/settings'
      path: '/settings'
      fullPath: '/orgs/$org/organization/settings'
      preLoaderRoute: typeof OrgsOrgOrganizationSettingsRouteImport
      parentRoute: typeof OrgsOrgOrganizationRoute
    }
    '/orgs/$org/organization/invitations': {
      id: '/orgs/$org/organization/invitations'
      path: '/invitations'
      fullPath: '/orgs/$org/organization/invitations'
      preLoaderRoute: typeof OrgsOrgOrganizationInvitationsRouteImport
      parentRoute: typeof OrgsOrgOrganizationRoute
    }
    '/orgs/$org/incidents/$incidentUid': {
      id: '/orgs/$org/incidents/$incidentUid'
      path: '/$incidentUid'
      fullPath: '/orgs/$org/incidents/$incidentUid'
      preLoaderRoute: typeof OrgsOrgIncidentsIncidentUidRouteImport
      parentRoute: typeof OrgsOrgIncidentsRoute
    }
    '/orgs/$org/checks/new': {
      id: '/orgs/$org/checks/new'
      path: '/new'
      fullPath: '/orgs/$org/checks/new'
      preLoaderRoute: typeof OrgsOrgChecksNewRouteImport
      parentRoute: typeof OrgsOrgChecksRoute
    }
    '/orgs/$org/checks/$checkUid': {
      id: '/orgs/$org/checks/$checkUid'
      path: '/$checkUid'
      fullPath: '/orgs/$org/checks/$checkUid'
      preLoaderRoute: typeof OrgsOrgChecksCheckUidRouteImport
      parentRoute: typeof OrgsOrgChecksRoute
    }
    '/orgs/$org/account/tokens': {
      id: '/orgs/$org/account/tokens'
      path: '/tokens'
      fullPath: '/orgs/$org/account/tokens'
      preLoaderRoute: typeof OrgsOrgAccountTokensRouteImport
      parentRoute: typeof OrgsOrgAccountRoute
    }
    '/orgs/$org/account/profile': {
      id: '/orgs/$org/account/profile'
      path: '/profile'
      fullPath: '/orgs/$org/account/profile'
      preLoaderRoute: typeof OrgsOrgAccountProfileRouteImport
      parentRoute: typeof OrgsOrgAccountRoute
    }
    '/orgs/$org/status-pages/$statusPageUid/': {
      id: '/orgs/$org/status-pages/$statusPageUid/'
      path: '/'
      fullPath: '/orgs/$org/status-pages/$statusPageUid/'
      preLoaderRoute: typeof OrgsOrgStatusPagesStatusPageUidIndexRouteImport
      parentRoute: typeof OrgsOrgStatusPagesStatusPageUidRoute
    }
    '/orgs/$org/checks/$checkUid/': {
      id: '/orgs/$org/checks/$checkUid/'
      path: '/'
      fullPath: '/orgs/$org/checks/$checkUid/'
      preLoaderRoute: typeof OrgsOrgChecksCheckUidIndexRouteImport
      parentRoute: typeof OrgsOrgChecksCheckUidRoute
    }
    '/orgs/$org/status-pages/$statusPageUid/edit': {
      id: '/orgs/$org/status-pages/$statusPageUid/edit'
      path: '/edit'
      fullPath: '/orgs/$org/status-pages/$statusPageUid/edit'
      preLoaderRoute: typeof OrgsOrgStatusPagesStatusPageUidEditRouteImport
      parentRoute: typeof OrgsOrgStatusPagesStatusPageUidRoute
    }
    '/orgs/$org/checks/$checkUid/edit': {
      id: '/orgs/$org/checks/$checkUid/edit'
      path: '/edit'
      fullPath: '/orgs/$org/checks/$checkUid/edit'
      preLoaderRoute: typeof OrgsOrgChecksCheckUidEditRouteImport
      parentRoute: typeof OrgsOrgChecksCheckUidRoute
    }
    '/orgs/$org/checks/$checkUid/results/$resultUid': {
      id: '/orgs/$org/checks/$checkUid/results/$resultUid'
      path: '/results/$resultUid'
      fullPath: '/orgs/$org/checks/$checkUid/results/$resultUid'
      preLoaderRoute: typeof OrgsOrgChecksCheckUidResultsResultUidRouteImport
      parentRoute: typeof OrgsOrgChecksCheckUidRoute
    }
  }
}

interface OrgsOrgAccountRouteChildren {
  OrgsOrgAccountProfileRoute: typeof OrgsOrgAccountProfileRoute
  OrgsOrgAccountTokensRoute: typeof OrgsOrgAccountTokensRoute
  OrgsOrgAccountIndexRoute: typeof OrgsOrgAccountIndexRoute
}

const OrgsOrgAccountRouteChildren: OrgsOrgAccountRouteChildren = {
  OrgsOrgAccountProfileRoute: OrgsOrgAccountProfileRoute,
  OrgsOrgAccountTokensRoute: OrgsOrgAccountTokensRoute,
  OrgsOrgAccountIndexRoute: OrgsOrgAccountIndexRoute,
}

const OrgsOrgAccountRouteWithChildren = OrgsOrgAccountRoute._addFileChildren(
  OrgsOrgAccountRouteChildren,
)

interface OrgsOrgChecksCheckUidRouteChildren {
  OrgsOrgChecksCheckUidEditRoute: typeof OrgsOrgChecksCheckUidEditRoute
  OrgsOrgChecksCheckUidIndexRoute: typeof OrgsOrgChecksCheckUidIndexRoute
  OrgsOrgChecksCheckUidResultsResultUidRoute: typeof OrgsOrgChecksCheckUidResultsResultUidRoute
}

const OrgsOrgChecksCheckUidRouteChildren: OrgsOrgChecksCheckUidRouteChildren = {
  OrgsOrgChecksCheckUidEditRoute: OrgsOrgChecksCheckUidEditRoute,
  OrgsOrgChecksCheckUidIndexRoute: OrgsOrgChecksCheckUidIndexRoute,
  OrgsOrgChecksCheckUidResultsResultUidRoute:
    OrgsOrgChecksCheckUidResultsResultUidRoute,
}

const OrgsOrgChecksCheckUidRouteWithChildren =
  OrgsOrgChecksCheckUidRoute._addFileChildren(
    OrgsOrgChecksCheckUidRouteChildren,
  )

interface OrgsOrgChecksRouteChildren {
  OrgsOrgChecksCheckUidRoute: typeof OrgsOrgChecksCheckUidRouteWithChildren
  OrgsOrgChecksNewRoute: typeof OrgsOrgChecksNewRoute
  OrgsOrgChecksIndexRoute: typeof OrgsOrgChecksIndexRoute
}

const OrgsOrgChecksRouteChildren: OrgsOrgChecksRouteChildren = {
  OrgsOrgChecksCheckUidRoute: OrgsOrgChecksCheckUidRouteWithChildren,
  OrgsOrgChecksNewRoute: OrgsOrgChecksNewRoute,
  OrgsOrgChecksIndexRoute: OrgsOrgChecksIndexRoute,
}

const OrgsOrgChecksRouteWithChildren = OrgsOrgChecksRoute._addFileChildren(
  OrgsOrgChecksRouteChildren,
)

interface OrgsOrgIncidentsRouteChildren {
  OrgsOrgIncidentsIncidentUidRoute: typeof OrgsOrgIncidentsIncidentUidRoute
  OrgsOrgIncidentsIndexRoute: typeof OrgsOrgIncidentsIndexRoute
}

const OrgsOrgIncidentsRouteChildren: OrgsOrgIncidentsRouteChildren = {
  OrgsOrgIncidentsIncidentUidRoute: OrgsOrgIncidentsIncidentUidRoute,
  OrgsOrgIncidentsIndexRoute: OrgsOrgIncidentsIndexRoute,
}

const OrgsOrgIncidentsRouteWithChildren =
  OrgsOrgIncidentsRoute._addFileChildren(OrgsOrgIncidentsRouteChildren)

interface OrgsOrgOrganizationRouteChildren {
  OrgsOrgOrganizationInvitationsRoute: typeof OrgsOrgOrganizationInvitationsRoute
  OrgsOrgOrganizationSettingsRoute: typeof OrgsOrgOrganizationSettingsRoute
  OrgsOrgOrganizationIndexRoute: typeof OrgsOrgOrganizationIndexRoute
}

const OrgsOrgOrganizationRouteChildren: OrgsOrgOrganizationRouteChildren = {
  OrgsOrgOrganizationInvitationsRoute: OrgsOrgOrganizationInvitationsRoute,
  OrgsOrgOrganizationSettingsRoute: OrgsOrgOrganizationSettingsRoute,
  OrgsOrgOrganizationIndexRoute: OrgsOrgOrganizationIndexRoute,
}

const OrgsOrgOrganizationRouteWithChildren =
  OrgsOrgOrganizationRoute._addFileChildren(OrgsOrgOrganizationRouteChildren)

interface OrgsOrgServerRouteChildren {
  OrgsOrgServerAuthRoute: typeof OrgsOrgServerAuthRoute
  OrgsOrgServerEmailInboxRoute: typeof OrgsOrgServerEmailInboxRoute
  OrgsOrgServerMailRoute: typeof OrgsOrgServerMailRoute
  OrgsOrgServerPerformanceRoute: typeof OrgsOrgServerPerformanceRoute
  OrgsOrgServerWebRoute: typeof OrgsOrgServerWebRoute
  OrgsOrgServerIndexRoute: typeof OrgsOrgServerIndexRoute
}

const OrgsOrgServerRouteChildren: OrgsOrgServerRouteChildren = {
  OrgsOrgServerAuthRoute: OrgsOrgServerAuthRoute,
  OrgsOrgServerEmailInboxRoute: OrgsOrgServerEmailInboxRoute,
  OrgsOrgServerMailRoute: OrgsOrgServerMailRoute,
  OrgsOrgServerPerformanceRoute: OrgsOrgServerPerformanceRoute,
  OrgsOrgServerWebRoute: OrgsOrgServerWebRoute,
  OrgsOrgServerIndexRoute: OrgsOrgServerIndexRoute,
}

const OrgsOrgServerRouteWithChildren = OrgsOrgServerRoute._addFileChildren(
  OrgsOrgServerRouteChildren,
)

interface OrgsOrgStatusPagesStatusPageUidRouteChildren {
  OrgsOrgStatusPagesStatusPageUidEditRoute: typeof OrgsOrgStatusPagesStatusPageUidEditRoute
  OrgsOrgStatusPagesStatusPageUidIndexRoute: typeof OrgsOrgStatusPagesStatusPageUidIndexRoute
}

const OrgsOrgStatusPagesStatusPageUidRouteChildren: OrgsOrgStatusPagesStatusPageUidRouteChildren =
  {
    OrgsOrgStatusPagesStatusPageUidEditRoute:
      OrgsOrgStatusPagesStatusPageUidEditRoute,
    OrgsOrgStatusPagesStatusPageUidIndexRoute:
      OrgsOrgStatusPagesStatusPageUidIndexRoute,
  }

const OrgsOrgStatusPagesStatusPageUidRouteWithChildren =
  OrgsOrgStatusPagesStatusPageUidRoute._addFileChildren(
    OrgsOrgStatusPagesStatusPageUidRouteChildren,
  )

interface OrgsOrgStatusPagesRouteChildren {
  OrgsOrgStatusPagesStatusPageUidRoute: typeof OrgsOrgStatusPagesStatusPageUidRouteWithChildren
  OrgsOrgStatusPagesNewRoute: typeof OrgsOrgStatusPagesNewRoute
  OrgsOrgStatusPagesIndexRoute: typeof OrgsOrgStatusPagesIndexRoute
}

const OrgsOrgStatusPagesRouteChildren: OrgsOrgStatusPagesRouteChildren = {
  OrgsOrgStatusPagesStatusPageUidRoute:
    OrgsOrgStatusPagesStatusPageUidRouteWithChildren,
  OrgsOrgStatusPagesNewRoute: OrgsOrgStatusPagesNewRoute,
  OrgsOrgStatusPagesIndexRoute: OrgsOrgStatusPagesIndexRoute,
}

const OrgsOrgStatusPagesRouteWithChildren =
  OrgsOrgStatusPagesRoute._addFileChildren(OrgsOrgStatusPagesRouteChildren)

interface OrgsOrgTestRouteChildren {
  OrgsOrgTestBulkRoute: typeof OrgsOrgTestBulkRoute
  OrgsOrgTestGenerateRoute: typeof OrgsOrgTestGenerateRoute
  OrgsOrgTestResetRoute: typeof OrgsOrgTestResetRoute
  OrgsOrgTestTemplatesRoute: typeof OrgsOrgTestTemplatesRoute
  OrgsOrgTestIndexRoute: typeof OrgsOrgTestIndexRoute
}

const OrgsOrgTestRouteChildren: OrgsOrgTestRouteChildren = {
  OrgsOrgTestBulkRoute: OrgsOrgTestBulkRoute,
  OrgsOrgTestGenerateRoute: OrgsOrgTestGenerateRoute,
  OrgsOrgTestResetRoute: OrgsOrgTestResetRoute,
  OrgsOrgTestTemplatesRoute: OrgsOrgTestTemplatesRoute,
  OrgsOrgTestIndexRoute: OrgsOrgTestIndexRoute,
}

const OrgsOrgTestRouteWithChildren = OrgsOrgTestRoute._addFileChildren(
  OrgsOrgTestRouteChildren,
)

interface OrgsOrgRouteChildren {
  OrgsOrgAccountRoute: typeof OrgsOrgAccountRouteWithChildren
  OrgsOrgBadgesRoute: typeof OrgsOrgBadgesRoute
  OrgsOrgChecksRoute: typeof OrgsOrgChecksRouteWithChildren
  OrgsOrgEventsRoute: typeof OrgsOrgEventsRoute
  OrgsOrgIncidentsRoute: typeof OrgsOrgIncidentsRouteWithChildren
  OrgsOrgLoginRoute: typeof OrgsOrgLoginRoute
  OrgsOrgOrganizationRoute: typeof OrgsOrgOrganizationRouteWithChildren
  OrgsOrgRegisterRoute: typeof OrgsOrgRegisterRoute
  OrgsOrgServerRoute: typeof OrgsOrgServerRouteWithChildren
  OrgsOrgStatusPagesRoute: typeof OrgsOrgStatusPagesRouteWithChildren
  OrgsOrgTestRoute: typeof OrgsOrgTestRouteWithChildren
  OrgsOrgIndexRoute: typeof OrgsOrgIndexRoute
}

const OrgsOrgRouteChildren: OrgsOrgRouteChildren = {
  OrgsOrgAccountRoute: OrgsOrgAccountRouteWithChildren,
  OrgsOrgBadgesRoute: OrgsOrgBadgesRoute,
  OrgsOrgChecksRoute: OrgsOrgChecksRouteWithChildren,
  OrgsOrgEventsRoute: OrgsOrgEventsRoute,
  OrgsOrgIncidentsRoute: OrgsOrgIncidentsRouteWithChildren,
  OrgsOrgLoginRoute: OrgsOrgLoginRoute,
  OrgsOrgOrganizationRoute: OrgsOrgOrganizationRouteWithChildren,
  OrgsOrgRegisterRoute: OrgsOrgRegisterRoute,
  OrgsOrgServerRoute: OrgsOrgServerRouteWithChildren,
  OrgsOrgStatusPagesRoute: OrgsOrgStatusPagesRouteWithChildren,
  OrgsOrgTestRoute: OrgsOrgTestRouteWithChildren,
  OrgsOrgIndexRoute: OrgsOrgIndexRoute,
}

const OrgsOrgRouteWithChildren =
  OrgsOrgRoute._addFileChildren(OrgsOrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NoOrgRoute: NoOrgRoute,
  ConfirmRegistrationTokenRoute: ConfirmRegistrationTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
  OrgsOrgRoute: OrgsOrgRouteWithChildren,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  AuthSlackCompleteRoute: AuthSlackCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
