import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The sidebar is autogenerated from the docs/ folder structure and the
// _category_.json files within it (Installation, Configuration, Features).
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
