import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Generated by `docusaurus gen-api-docs` (docusaurus-plugin-openapi-docs) into
// the gitignored docs/api/. It is one doc item for the intro page followed by
// one category per OpenAPI tag. `bun run build`, `bun run start` and
// `bun run typecheck` all run gen-api-docs first, so this import always
// resolves — see package.json.
import apiSidebar from "./docs/api/sidebar";

// The generated slice leads with the intro page (docs/api/*.info.mdx, slug
// /api). We lift it out of the item list and use it as the category's link, so
// clicking "API Reference" lands on the reference's front page instead of just
// expanding a spindown — and so the page's own <DocCardList> lists the tag
// groups rather than listing itself.
const [firstItem, ...restItems] = apiSidebar;
const introItem =
  typeof firstItem === "object" && firstItem.type === "doc" ? firstItem : undefined;

const apiCategory = {
  type: "category" as const,
  // Keep in sync with API_REFERENCE_LABEL in docusaurus.config.ts, which filters
  // the autogenerated copy of this category out of the tree.
  label: "API Reference",
  collapsed: true,
  ...(introItem ? { link: { type: "doc" as const, id: introItem.id } } : {}),
  items: introItem ? restItems : apiSidebar,
};

// Everything except the API reference is autogenerated from the docs/ folder
// structure and its _category_.json files (Installation, Configuration,
// Features). The reference is appended explicitly, last.
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }, apiCategory],
};

export default sidebars;
