package app

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestDocsHostMatches(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		reqHost  string
		docsHost string
		want     bool
	}{
		{name: "exact match", reqHost: "docs.solidping.io", docsHost: "docs.solidping.io", want: true},
		{name: "host with port", reqHost: "docs.solidping.io:443", docsHost: "docs.solidping.io", want: true},
		{name: "case insensitive", reqHost: "Docs.SolidPing.IO", docsHost: "docs.solidping.io", want: true},
		{name: "different host", reqHost: "www.solidping.io", docsHost: "docs.solidping.io", want: false},
		{name: "app host with port", reqHost: "app.solidping.io:4000", docsHost: "docs.solidping.io", want: false},
		{name: "empty request host", reqHost: "", docsHost: "docs.solidping.io", want: false},
	}

	for _, testCase := range tests {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()
			r := require.New(t)
			r.Equal(testCase.want, docsHostMatches(testCase.reqHost, testCase.docsHost))
		})
	}
}

// TestEmbeddedDocsContainSearchIndex guards the @easyops-cn/docusaurus-search-local
// build output: the offline lunr index is a static asset generated by
// `make build-docs` into the Docusaurus build dir and copied into
// docsres/ by `make copy-docs`, so it ends up in the embedded FS with no
// runtime/server changes. If a future docs-pipeline or theme-config change
// silently stops emitting it, this fails CI instead of quietly shipping a
// docs site with no search. The CI lint/test job seeds a placeholder
// docsres/ (see .github/workflows/ci.yml) that includes an empty
// search-index.json, so this test passes there too without a real docs build.
func TestEmbeddedDocsContainSearchIndex(t *testing.T) {
	t.Parallel()
	r := require.New(t)

	_, err := docsFiles.ReadFile("docsres/search-index.json")
	r.NoError(err, "embedded docs must contain the offline search index (search-index.json)")
}
