package app

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// TestServeRootLLMsTxt covers GitHub issue #183: llms.txt and llms-full.txt,
// generated by docusaurus-plugin-llms into the embedded docs build, must be
// reachable at the conventional root path (not just under /docs), and a
// missing file must 404 rather than fall through to the SPA shell.
func TestServeRootLLMsTxt(t *testing.T) {
	t.Parallel()
	r := require.New(t)

	s := &Server{}

	req := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/llms.txt", http.NoBody)
	w := httptest.NewRecorder()
	r.NoError(s.serveRootLLMsTxt(w, req))

	resp := w.Result()
	defer func() { _ = resp.Body.Close() }()

	r.Equal(http.StatusOK, resp.StatusCode)
	r.Contains(resp.Header.Get("Content-Type"), "text/plain")
	r.True(strings.HasPrefix(w.Body.String(), "# SolidPing"),
		"body should start with the docs title, got: %.80s", w.Body.String())
}

func TestServeRootLLMsFullTxt(t *testing.T) {
	t.Parallel()
	r := require.New(t)

	s := &Server{}

	req := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/llms-full.txt", http.NoBody)
	w := httptest.NewRecorder()
	r.NoError(s.serveRootLLMsFullTxt(w, req))

	resp := w.Result()
	defer func() { _ = resp.Body.Close() }()

	r.Equal(http.StatusOK, resp.StatusCode)
	r.Contains(resp.Header.Get("Content-Type"), "text/plain")
	r.True(strings.HasPrefix(w.Body.String(), "# SolidPing"),
		"body should start with the docs title, got: %.80s", w.Body.String())
}

// TestServeDocsLLMsTxtStillWorks verifies /docs/llms.txt keeps working
// unchanged now that /llms.txt is also served at the root.
func TestServeDocsLLMsTxtStillWorks(t *testing.T) {
	t.Parallel()
	r := require.New(t)

	s := &Server{}

	req := httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/docs/llms.txt", http.NoBody)
	w := httptest.NewRecorder()
	r.NoError(s.serveDocsRoute(w, req))

	resp := w.Result()
	defer func() { _ = resp.Body.Close() }()

	r.Equal(http.StatusOK, resp.StatusCode)
	r.Contains(resp.Header.Get("Content-Type"), "text/plain")
	r.True(strings.HasPrefix(w.Body.String(), "# SolidPing"),
		"body should start with the docs title, got: %.80s", w.Body.String())
}

// TestServeRootLLMsTxtMissingFile404s asserts a missing root docs file 404s
// (via the docs 404 page) rather than falling through to the SPA shell.
func TestServeRootLLMsTxtMissingFile404s(t *testing.T) {
	t.Parallel()
	r := require.New(t)

	s := &Server{}

	w := httptest.NewRecorder()
	s.serveDocsFile(w, "/llms-does-not-exist.txt")

	resp := w.Result()
	defer func() { _ = resp.Body.Close() }()

	r.Equal(http.StatusNotFound, resp.StatusCode)
}
