// Package models provides data models for the SolidPing database.
package models

import (
	"time"

	"github.com/google/uuid"
)

// StatusUpdateKind represents the kind of a status update.
type StatusUpdateKind string

const (
	// StatusUpdateKindInvestigating indicates the team is investigating.
	StatusUpdateKindInvestigating StatusUpdateKind = "investigating"
	// StatusUpdateKindIdentified indicates the issue has been identified.
	StatusUpdateKindIdentified StatusUpdateKind = "identified"
	// StatusUpdateKindMonitoring indicates the fix is being monitored.
	StatusUpdateKindMonitoring StatusUpdateKind = "monitoring"
	// StatusUpdateKindResolved indicates the issue is resolved.
	StatusUpdateKindResolved StatusUpdateKind = "resolved"
	// StatusUpdateKindMaintenance indicates a scheduled maintenance.
	StatusUpdateKindMaintenance StatusUpdateKind = "maintenance"
	// StatusUpdateKindInfo is a general informational update.
	StatusUpdateKindInfo StatusUpdateKind = "info"
)

// IsValid returns true if the kind is one of the recognized values.
func (k StatusUpdateKind) IsValid() bool {
	switch k {
	case StatusUpdateKindInvestigating, StatusUpdateKindIdentified,
		StatusUpdateKindMonitoring, StatusUpdateKindResolved,
		StatusUpdateKindMaintenance, StatusUpdateKindInfo:
		return true
	default:
		return false
	}
}

// StatusUpdate is an operator-written narrative post anchored to a status page.
type StatusUpdate struct {
	UID             string  `bun:"uid,pk,type:varchar(36)"`
	OrganizationUID string  `bun:"organization_uid,notnull"`
	StatusPageUID   string  `bun:"status_page_uid,notnull"`
	SectionUID      *string `bun:"section_uid"`  // optional: scope to section
	CheckUID        *string `bun:"check_uid"`    // optional: scope to check
	IncidentUID     *string `bun:"incident_uid"` // optional: thread under incident
	// IncidentPublicationUID threads the update under a publication. A
	// hand-authored publication has no incident to thread on, so this is the
	// only link it gets (spec 2026-08-19-08).
	IncidentPublicationUID *string          `bun:"incident_publication_uid"`
	Title                  string           `bun:"title,notnull"`
	BodyMarkdown           string           `bun:"body_markdown,notnull"`
	LinkURL                *string          `bun:"link_url"`
	Kind                   StatusUpdateKind `bun:"kind,notnull"`
	PublishedAt            time.Time        `bun:"published_at,notnull,default:current_timestamp"`
	// AuthorUID is the user who posted the update. nil = generated by the
	// auto-publish pipeline: a machine post has no author, and attributing it
	// to whichever human happens to own the org would be a lie the UI renders.
	AuthorUID *string    `bun:"author_uid"`
	CreatedAt time.Time  `bun:"created_at,notnull,default:current_timestamp"`
	UpdatedAt time.Time  `bun:"updated_at,notnull,default:current_timestamp"`
	DeletedAt *time.Time `bun:"deleted_at"`
}

// NewStatusUpdate creates a new StatusUpdate with generated UID and timestamps.
func NewStatusUpdate(orgUID, statusPageUID, authorUID string) *StatusUpdate {
	now := time.Now()

	var author *string
	if authorUID != "" {
		author = &authorUID
	}

	return &StatusUpdate{
		UID:             uuid.New().String(),
		OrganizationUID: orgUID,
		StatusPageUID:   statusPageUID,
		AuthorUID:       author,
		PublishedAt:     now,
		CreatedAt:       now,
		UpdatedAt:       now,
	}
}

// StatusUpdatesFilter configures what to return from ListStatusUpdates.
type StatusUpdatesFilter struct {
	StatusPageUID string
	SectionUID    *string
	CheckUID      *string
	IncidentUID   *string
	// IncidentPublicationUID filters to one publication's thread.
	IncidentPublicationUID *string
	Limit                  int
	Offset                 int
}
