/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgRouteImport } from './routes/$org'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgIndexRouteImport } from './routes/$org.index'
import { Route as OrgSlugRouteImport } from './routes/$org.$slug'

const OrgRoute = OrgRouteImport.update({
  id: '/$org',
  path: '/$org',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgRoute,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OrgRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$org': typeof OrgRouteWithChildren
  '/$org/$slug': typeof OrgSlugRoute
  '/$org/': typeof OrgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$org/$slug': typeof OrgSlugRoute
  '/$org': typeof OrgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$org': typeof OrgRouteWithChildren
  '/$org/$slug': typeof OrgSlugRoute
  '/$org/': typeof OrgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$org' | '/$org/$slug' | '/$org/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$org/$slug' | '/$org'
  id: '__root__' | '/' | '/$org' | '/$org/$slug' | '/$org/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgRoute: typeof OrgRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$org': {
      id: '/$org'
      path: '/$org'
      fullPath: '/$org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/': {
      id: '/$org/'
      path: '/'
      fullPath: '/$org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/$slug': {
      id: '/$org/$slug'
      path: '/$slug'
      fullPath: '/$org/$slug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof OrgRoute
    }
  }
}

interface OrgRouteChildren {
  OrgSlugRoute: typeof OrgSlugRoute
  OrgIndexRoute: typeof OrgIndexRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgSlugRoute: OrgSlugRoute,
  OrgIndexRoute: OrgIndexRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgRoute: OrgRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
