#!/usr/bin/env bun
/**
 * Generate web/docs/docs/changelog.md from the root CHANGELOG.md.
 *
 * Run at build time (see the `build` and `start` scripts in package.json) so
 * the docs page can never drift from whatever release-please last wrote —
 * there is no manually-maintained copy. The generated file is gitignored
 * (see .gitignore's `/docs/changelog.md` entry); this script is the only
 * thing that writes it.
 *
 * The actual transform logic lives in ../src/lib/changelog.ts, where it is
 * unit-tested (`bun test ./src`) independently of this file I/O wrapper.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { transformChangelog } from "../src/lib/changelog";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const rootChangelogPath = join(scriptDir, "..", "..", "..", "CHANGELOG.md");
const outputPath = join(scriptDir, "..", "docs", "changelog.md");

async function main() {
  let raw: string;
  try {
    raw = await readFile(rootChangelogPath, "utf8");
  } catch (err) {
    // The changelog is generated content, not something a docs build should
    // ever hard-fail over — fall back to a minimal placeholder page instead.
    console.warn(
      `[gen-changelog] could not read ${rootChangelogPath}, writing a placeholder page:`,
      err,
    );
    raw = "# Changelog\n\nNo changelog available yet.\n";
  }

  let body: string;
  try {
    body = transformChangelog(raw);
  } catch (err) {
    console.warn(
      "[gen-changelog] transform threw unexpectedly, falling back to the raw changelog verbatim:",
      err,
    );
    body = raw.trim() + "\n";
  }

  const frontmatter = [
    "---",
    "title: Changelog",
    // Deliberately high so this always sorts last among the top-level docs
    // pages in the autogenerated sidebar.
    "sidebar_position: 1000",
    // Compiled as CommonMark, not MDX — this page is generated from prose
    // nobody proofreads for MDX-safety (stray `<name>` / `{...}` are
    // routine in release notes), so it must be immune to that by
    // construction rather than by convention.
    "format: md",
    "---",
    "",
  ].join("\n");

  const page = `${frontmatter}# Changelog\n\n${body}`;

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, page, "utf8");
  console.log(`[gen-changelog] wrote ${outputPath}`);
}

await main();
